image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 8025
    onOpen: ignore
  - port: 1025
    onOpen: ignore
  - port: 9000
    onOpen: ignore

tasks:
  - init: >
      gp await-port 3306 && # Await MySQL load
      wp-setup-theme && # Setup the theme
      cd /workspace/stcblog/public_html &&
      wp theme activate stcblog && # Activate our theme
      wp option set blogname studuj.digital &&
      wp option set blogdescription "Články, novinky, tipy a triky z dílny studentů Microsoft STC o moderních technologiích. Studuj s námi digitálně!" &&
      wp rewrite structure /%year%/%monthnum%/%day%/%postname%/ && # Set permalink structure
      wp post delete 1 &&
      wget https://shareefiles.blob.core.windows.net/files/9j500a.xml && # Get the dummy config file
      wget https://github.com/filiptronicek/pixasplash-wordpress/releases/latest/download/pixasplash-wordpress.zip &&
      wp plugin install pixasplash-wordpress.zip --activate &&
      wp plugin install wordpress-importer --activate &&
      wp plugin install syntaxhighlighter --activate &&
      wp plugin install easy-table-of-contents --activate &&
      #wp plugin install automatic-nbsp --activate &&
      wp plugin install yet-another-related-posts-plugin --activate &&
      wp plugin install wp-external-links --activate &&
      wp import 9j500a.xml --authors=create # Import dummy posts and menus
    command: apache2ctl start # start Apache server
  
  # start MailHog (SMTP testing tool) 
  - command: mailhog -api-bind-addr 127.0.0.1:8025 -ui-bind-addr 127.0.0.1:8025 -smtp-bind-addr 127.0.0.1:1025

vscode:
  extensions:
    - glenn2223.live-sass@4.3.4:oSIVGGL6KX7O0jzLr2O0TA==
